// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu7zhYnVbJwCj3BVS49lzTj3E1au7oYEA',
    appId: '1:754795721998:web:f0ec3294aa09e3edb6935f',
    messagingSenderId: '754795721998',
    projectId: 'tasks-ibrahem',
    authDomain: 'tasks-ibrahem.firebaseapp.com',
    storageBucket: 'tasks-ibrahem.firebasestorage.app',
    measurementId: 'G-2RTRRVJVJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi3g0NEf1UoQD-Rvqh-W2dv39nW4sY4Xc',
    appId: '1:754795721998:android:9ad14191386b5243b6935f',
    messagingSenderId: '754795721998',
    projectId: 'tasks-ibrahem',
    storageBucket: 'tasks-ibrahem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-jBV2kMr9N2euFYNS5JsRyZ-4Molf92o',
    appId: '1:754795721998:ios:89d1df982510d2feb6935f',
    messagingSenderId: '754795721998',
    projectId: 'tasks-ibrahem',
    storageBucket: 'tasks-ibrahem.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-jBV2kMr9N2euFYNS5JsRyZ-4Molf92o',
    appId: '1:754795721998:ios:89d1df982510d2feb6935f',
    messagingSenderId: '754795721998',
    projectId: 'tasks-ibrahem',
    storageBucket: 'tasks-ibrahem.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu7zhYnVbJwCj3BVS49lzTj3E1au7oYEA',
    appId: '1:754795721998:web:cc1e88640be6cfc6b6935f',
    messagingSenderId: '754795721998',
    projectId: 'tasks-ibrahem',
    authDomain: 'tasks-ibrahem.firebaseapp.com',
    storageBucket: 'tasks-ibrahem.firebasestorage.app',
    measurementId: 'G-2W8322LEDR',
  );
}
